### ISSUE TITLE
Potential Issue

### ISSUE THREAD

**Issue by sno0ose** [n00py/WPForce#1]
I am testing a site with admin and a user. The output with -v is showing it test admin the user and no user. 

![screen shot 2017-04-10 at 8 31 21 pm 3](https://cloud.githubusercontent.com/assets/7998042/24888988/f5a488e0-1e2c-11e7-998d-ea35621202e9.png)

**Comment by n00py** [comment]
By any chance do you have a line break at the end of your file?  I think it may be reading in a blank line.

**Comment by sno0ose** [comment]
not by the vi output

**Comment by sno0ose** [comment]
output I just got after removing the extra user - now just admin 

Trying admin : 0841667990
Trying admin : 073837401
Trying admin : 04162864555
Trying admin : 014712972
Trying  : 082601lete
Trying  : 231202
Trying  : 711208lete
Trying  : booty56ete
Trying  : megalina
Trying  : wnm4716
Trying  : lila28
Trying  : yoshit
Trying  : 123456
Trying  : titisorete
Trying  : noraekin
Trying  : shepherd01
Trying  : booyah69
Trying  : ilimamfete
Trying  : badazz225e
Trying  : desroches
Exception in thread Thread-32:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "wpforce.py", line 61, in worker
    PasswordAttempt(user,password,url,thread_no,verbose,debug,agent)
  File "wpforce.py", line 149, in PasswordAttempt
    if e.code == 404 or e.code == 403:
AttributeError: 'URLError' object has no attribute 'code'

**Comment by sno0ose** [comment]
I updated the thread with some output

**Comment by n00py** [comment]
I'll look into it this weekend to see what might cause the blank username issue.

As far as threads go, anything over 10 doesn't do so well in most of my times using it.

**Comment by n00py** [comment]
This should be fixed now.
