### ISSUE TITLE
No license and version numbering

### ISSUE THREAD

**Issue by mboelen** [n00py/WPForce#2]
Your project is being reviewed for a new security-related website I'm working on. Due to the license missing (both here and in the code or on the screen output), it is unclear how people can use the software. Also, a version number is missing.

Can you select a license and add it to the project? For version numbers, the [semantic version numbering](http://semver.org/) is typically advised.

Thanks for your project!

**Comment by n00py** [comment]
I've added a license and applied a version number to the source code.
