### ISSUE TITLE
Add an option (suggestion)

### ISSUE THREAD

**Issue by syrius01** [n00py/WPForce#6]
Hi,

First I wanted to thank you for this awesome tool. Would it be possible to add an option for running WPForce with all WordPress urls in a file?

e.g. : python wpforce.py -i usr.txt -w passwd.txt -f filename-containing-urls.txt

This would be awesome. Thanks again.

**Comment by n00py** [comment]
Hello,

I don't think I will add this as it's a little too far outside of what I designed it for, but I can suggest a way you could do this in bash.  

You could plrably make something like this:

while read filename-containing-urls.txt ; do python wpforce.py -i usr.txt -w passwd.txt -f $i ; done < filename-containing-urls.txt

That syntax might be a bit off but that would be the basic idea

**Comment by syrius01** [comment]
Thanks for your quick reply.  I get this msg:

line 1: read: `url3.txt': not a valid identifier
