### ISSUE TITLE
Proxy list support

### ISSUE THREAD

**Issue by AiratHalitov** [n00py/WPForce#9]
Hi, thanks for good solution! 
How can I use proxy list? 
Can you add proxy support?
You can use flag:
**-p proxy-list.txt**

**Comment by n00py** [comment]
Hello, This probably won't be a feature I will add, as it seems to exclusively benefit unauthorized attackers. Right now your best bet for hidden origin is probably to use proxychains or run a VPN, or forking the script and modifying it.

**Comment by AiratHalitov** [comment]
Here is some example https://github.com/N3TC4T/InstaBrute
